apiVersion: v1
data:
  mapRoles: |
    - groups: 
      - system:masters
      rolearn: arn:aws:iam::242485614316:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::242485614316:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KZRBTA3ANWAT
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-23T07:47:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "859"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9b9ef592-6cda-11ea-bdbc-0af75c711be6
